export const PROCTOR_EVENTS = {
  // Detection
  DETECTION_UPDATED: "DETECTION_UPDATED",

  // Media
  MEDIA_PIPE_READY: "MEDIA_PIPE_READY",
  MEDIA_PIPE_ERROR: "MEDIA_PIPE_ERROR",

  // WebSocket
  WEBSOCKET_CONNECTED: "WEBSOCKET_CONNECTED",
  WEBSOCKET_DISCONNECTED: "WEBSOCKET_DISCONNECTED",

  // Streaming
  SNAPSHOT_SENT: "SNAPSHOT_SENT",
  SNAPSHOT_ERROR: "SNAPSHOT_ERROR",

  // ==========================
  // NEW EVENTS
  // ==========================

  WARNING_RECEIVED: "WARNING_RECEIVED",

  WARNING_UPDATED: "WARNING_UPDATED",

  EXAM_TERMINATED: "EXAM_TERMINATED",
};
