export const PROCTOR_EVENTS = {
  DETECTION_UPDATED: "DETECTION_UPDATED",
  MEDIA_PIPE_READY: "MEDIA_PIPE_READY",
  MEDIA_PIPE_ERROR: "MEDIA_PIPE_ERROR",
  WEBSOCKET_CONNECTED: "WEBSOCKET_CONNECTED",
  WEBSOCKET_DISCONNECTED: "WEBSOCKET_DISCONNECTED",
  SNAPSHOT_SENT: "SNAPSHOT_SENT",
  SNAPSHOT_ERROR: "SNAPSHOT_ERROR",
  WARNING_RECEIVED: "WARNING_RECEIVED",
  WARNING_UPDATED: "WARNING_UPDATED",
  EXAM_TERMINATED: "EXAM_TERMINATED",
};
